<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2018.1.0.386
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Order Form Form Submission',
	'heading' => 'New Form Submission',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => 'Checked',
		'checkbox_unchecked' => 'Unchecked',
		'submitted_from' => 'Form submitted from website: %s',
		'submitted_by' => 'Visitor IP address: %s',
		'too_many_submissions' => 'Too many recent submissions from this IP',
		'failed_to_send_email' => 'Failed to send email',
		'invalid_reCAPTCHA_private_key' => 'Invalid reCAPTCHA private key.',
		'invalid_reCAPTCHA2_private_key' => 'Invalid reCAPTCHA 2.0 private key.',
		'invalid_reCAPTCHA2_server_response' => 'Invalid reCAPTCHA 2.0 server response.',
		'invalid_field_type' => 'Unknown field type \'%s\'.',
		'invalid_form_config' => 'Field \'%s\' has an invalid configuration.',
		'unknown_method' => 'Unknown server request method'
	),
	'email' => array(
		'from' => '',
		'to' => ''
	),
	'fields' => array(
		'custom_U893' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'Message: Please enter name, address and any special instructions',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Message: Please enter name, address and any special instructions\' is required.'
			)
		),
		'custom_U979' => array(
			'order' => 2,
			'type' => 'checkbox',
			'label' => '8 pc Chicken Tenders and 1 Side  $8.500',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'8 pc Chicken Tenders and 1 Side  $8.500\' is required.'
			)
		),
		'custom_U1036' => array(
			'order' => 3,
			'type' => 'checkbox',
			'label' => '1/2 Chicken and 2 Sides  $11.50',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'1/2 Chicken and 2 Sides  $11.50\' is required.'
			)
		),
		'custom_U1048' => array(
			'order' => 4,
			'type' => 'checkbox',
			'label' => 'Pulled Pork Sandwich and 1 Side   $8.00',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Pulled Pork Sandwich and 1 Side   $8.00\' is required.'
			)
		),
		'custom_U1060' => array(
			'order' => 5,
			'type' => 'checkbox',
			'label' => 'Pulled Pork Dinner and 2 Sides  $11.00',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Pulled Pork Dinner and 2 Sides  $11.00\' is required.'
			)
		),
		'custom_U1072' => array(
			'order' => 6,
			'type' => 'checkbox',
			'label' => 'Beef Brisket Sandwich and 1 Side $12.00',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Beef Brisket Sandwich and 1 Side $12.00\' is required.'
			)
		),
		'custom_U1084' => array(
			'order' => 7,
			'type' => 'checkbox',
			'label' => 'Rib Tip Sandwich and 1 Side   $9.00',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Rib Tip Sandwich and 1 Side   $9.00\' is required.'
			)
		),
		'custom_U1096' => array(
			'order' => 8,
			'type' => 'checkbox',
			'label' => 'Rib Tip Dinner and 2 Sides $11.50',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Rib Tip Dinner and 2 Sides $11.50\' is required.'
			)
		),
		'custom_U1108' => array(
			'order' => 9,
			'type' => 'checkbox',
			'label' => 'Whole of Ribs @ 2 Sides $24.60',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Whole of Ribs @ 2 Sides $24.60\' is required.'
			)
		),
		'custom_U1120' => array(
			'order' => 10,
			'type' => 'checkbox',
			'label' => 'French Fries $1.99',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'French Fries $1.99\' is required.'
			)
		),
		'custom_U1132' => array(
			'order' => 11,
			'type' => 'checkbox',
			'label' => 'Baked Beans $2.39',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Baked Beans $2.39\' is required.'
			)
		)
	)
);

process_form($form);
?>
